### PR TITLE
Update PRIVACY.md

### PR DESCRIPTION
**Pull request by marcelgustin**
What is ment with "does it have a party" in line 14 and "Opened pipe select window" in line 26?

### CODE REVIEW

**Comment by maximmax42** [comment]
Party means if this is set to non-zero values:
image

Pipe select window opens when you press ctrl+shift+connect, it allows you to change the pipe presence connects to (basically, if you have more than one discord instance open at a time or if you use account switcher, different accounts are on different pipes).

I don't see type of device technically, in my dashboard I just see the device's model name that's set in BIOS. Laptops usually have it set as the actual model name, desktops have either "none" or "to be filled by oem" or motherboard model.

**Comment by maximmax42** [comment]
I mean it's not a feature that everyone needs to bother with, because not everyone uses more than one discord account, but for those who do, I have written about it in the [setting up guide](https://github.com/maximmax42/Discord-CustomRP/wiki/Setting-up#i-use-more-than-one-discord-client-what-do-i-do), I think that's enough.

**Comment by marcelgustin** [comment]
Okay alright

**Comment by maximmax42** [comment]
So uh, will you add anything else to this?

**Pull request merged**
