### PR TITLE
Update Strings.zh-Hant.resx

### PR DESCRIPTION
**Pull request by DragonTaki**
Fixed some Traditional Chinese words (from incorrect Simplified Chinese usage)

### CODE REVIEW

**Comment by maximmax42** [comment]
Can you please update these lines in POEditor project instead?
https://poeditor.com/join/project/2jq0i7ANr1

**Comment by DragonTaki** [comment]
Sure. Give me a second.

**Comment by maximmax42** [comment]
Oh and, if you want to be credited with a URL, you can send it here. I keep track of people's contributions and it's way easier when they're all done though one place (POEditor in this case).

**Comment by DragonTaki** [comment]
My POEditor username is "DragonTaki" (same as here).

**Comment by maximmax42** [comment]
Do you want to be credited with any URL?

**Comment by DragonTaki** [comment]
Sure.
Is any link acceptable?
https://steamcommunity.com/id/DragonTaki/

**Comment by maximmax42** [comment]
> Sure. Is any link acceptable? https://steamcommunity.com/id/DragonTaki/

Yeah. This works, thank you for your contribution!

**Comment by maximmax42** [comment]
Updated in d5f0a79

**Pull request closed without merging**
